Gives the player a starter for each region
pokeclicker/pokeclicker pull request #2091
Opened 2022-04-28 19:08 UTC by Jaaslet

Now the player can select a starter, for each region (requested by Ultima).
I could not come up with a fun text, so i just made a basic one. If someone has any ideas, feel free to share it, and i might use it.
![image](https://user-images.githubusercontent.com/2961347/165827922-64187d1c-3aad-4ad5-8f54-620a3f50be6d.png)

2022-04-28 23:39 UTC, Ultima1990 commented
Just a quick check, is this gonna allow the Pikachu option by closing the modal several times in every region? Probably wouldn't want that...

2022-04-28 23:46 UTC, Ultima1990 commented
Oh. OH! An idea has jumped into my brain. If we want to keep the sneaky 4th option thing going in every region, we can do the Capachus. And if you don't pick the Capachu you have to wait till Pikachu Valley to get it.

2022-04-29 00:34 UTC, RedSparr0w commented
I haven't had a chance to test this yet, but just a couple questions.
What happens for player who are already in newer regions, will they be asked to pick a starter for each of their previous regions on update?
What happens if you refresh the page while the new starter modal is shown, will it be shown when the load the game again?

2022-04-29 05:43 UTC, Jaaslet commented
> Just a quick check, is this gonna allow the Pikachu option by closing the modal several times in every region? Probably wouldn't want that...

I made a new window and new code for the other regions. The other one is a part of the tutorial, so it was different enough, that i did not want to reuse the code

2022-04-29 05:49 UTC, Jaaslet commented
> What happens for player who are already in newer regions, will they be asked to pick a starter for each of their previous regions on update? 

They don't get to pick a starter, and we pretend like they picked the first one in each region.

> What happens if you refresh the page while the new starter modal is shown, will it be shown when the load the game again?

Yeah... i got lazy... you don't get a starter, and we pretend like you picked the first. I was hoping no one refreshes their game here.
I can try to figure out a way to fix that. It might be easier to program, if we also want the window to show up for old players, for each region

2022-04-29 05:52 UTC, Jaaslet commented
> If we want to keep the sneaky 4th option thing going in every region, we can do the Capachus. And if you don't pick the Capachu you have to wait till Pikachu Valley to get it.

I liked playing though Pikachu Valley, so i don't like to ruin that experiance for players, who looked at the wiki for the optimal way to play

2022-05-08 19:52 UTC, Jaaslet commented
I have now fixed the refresh problem (see description for how).
The secret cap pikachu will not be a part of this PR (if we even want it).
So now it should be ready for review

2022-05-24 00:21 UTC, RedSparr0w commented on src/scripts/gym/Champion.ts
> -            case GameConstants.Starter.Bulbasaur: {
Are these still used anywhere now? or should they be removed from GameConstants too?

2022-05-24 00:21 UTC, RedSparr0w requested changes
At the moment, you can just click straight off the starter modal and it will disappear, we should probably disable this or make it re-appear until they choose a starter.

2022-05-24 07:50 UTC, Jaaslet commented
> At the moment, you can just click straight off the starter modal and it will disappear, we should probably disable this or make it re-appear until they choose a starter.

This comment is fixed. The other comment is waiting for a discord discussion

2022-05-26 02:35 UTC, RedSparr0w approved these changes
Looks good, Thanks for the PR! 👍

2022-05-26 02:36 UTC, merged