Some temporary battle fixes
pokeclicker/pokeclicker pull request #2164
Opened 2022-05-14 11:20 UTC by Ultima1990

Adds Ultra Wormhole sprite. Also used for Ultra Megalopolis. Very ugly. Anyone is free to make something better.
Turned Ultra Megalopolis into a one time battle. Removed Elite_UltraNecrozma badge.
Changed Eater of Light quest to target the TemporaryBattles instead of the Gyms.

2022-05-14 14:28 UTC, Someonealive-QN commented
Like this? 
![86 Sem Título_20220514112541](https://user-images.githubusercontent.com/97617298/168429978-31a7ca3a-2e4e-4cd4-b892-55b77b92d7a2.png)
 Ins't mine but the person who made them said its free to use 
![Screenshot_20220514-111344](https://user-images.githubusercontent.com/97617298/168430011-27e46ab6-257a-4a14-9e2b-7119ab55f1b0.jpg)
Here

2022-05-14 14:59 UTC, Ultima1990 commented
> Like this? ![86 Sem Título_20220514112541](https://user-images.githubusercontent.com/97617298/168429978-31a7ca3a-2e4e-4cd4-b892-55b77b92d7a2.png) Ins't mine but the person who made them said its free to use ![Screenshot_20220514-111344](https://user-images.githubusercontent.com/97617298/168430011-27e46ab6-257a-4a14-9e2b-7119ab55f1b0.jpg) Here

Link?

2022-05-14 15:02 UTC, Someonealive-QN commented
Here:
https://www.pokecommunity.com/showthread.php?p=9849231

2022-05-24 13:39 UTC, Jaaslet requested changes
You also need to remove 'Elite_UltraNecrozma' from badges.ts for it to work.
I have reviewed the code, tested the update function and tested it as a lategame player.
I have not yet tested if the quest still works

2022-05-24 13:39 UTC, Jaaslet commented on src/scripts/Update.ts
> +            saveData.statistics.temporaryBattleDefeated = new Array<number>();
This line needs to be removed. It's overwriting the Nihilego temp battle update

2022-05-24 13:39 UTC, Jaaslet commented on src/scripts/Update.ts
> +            saveData.statistics.temporaryBattleDefeated[1] = saveData.statistics.gymsDefeated[89];
Because Nihilego have been removed earlier in the update function, this gym now has index 88 and not index 89

2022-05-24 19:59 UTC, Jaaslet approved these changes
Looks good.
The update function now works and i have now also played though the quest as a new Alola player. It works just as before.
So i have no more comments

2022-05-26 02:26 UTC, merged