Project make people use the client
pokeclicker/pokeclicker pull request #2296
Opened 2022-05-28 00:22 UTC by Jaaslet

We want the players to atleast try out the client, to reduce server usage. This PR is trying to encourage people to use the client, but not force them to.

- [] Add client exclusive Pokemon
- [] Add way to obtain
- [] Add NPCs explaining the obtain way is exclusive
- [] Add link in the browser to the client
- [] Maybe more?

2022-06-12 06:18 UTC, RedSparr0w commented on src/components/saveSelector.html
> +            You can event find an client exclusive pokémon when you reach Sevii Island!
```suggestion
            To help reduce server load, please download our desktop client <a href="https://github.com/RedSparr0w/Pokeclicker-desktop/releases/latest" target="_blank">here</a>.
            You can event find a Pokémon exclusive to the client when you reach the Sevii Islands!
```

2022-10-29 19:09 UTC, erzads commented
I didn't know there was a client. Where can I find it?

2022-10-29 19:17 UTC, Aegyo commented
https://github.com/RedSparr0w/Pokeclicker-desktop/releases/latest

2022-11-10 21:19 UTC, Aegyo requested changes
Missing credit for the ~~pokemon and~~ island image~~s~~ (unless I'm blind?)

2022-11-10 21:39 UTC, Jaaslet commented
Credits added and merge conflicts resolved

2022-11-10 23:22 UTC, Aegyo approved these changes

2022-11-10 23:23 UTC, merged