Added CaptureSpecificPokemonQuest
pokeclicker/pokeclicker pull request #2380
Opened 2022-06-05 07:29 UTC by Jaaslet

Including a "ignore breeding"-parameter.
Needed for UB-PR, maybe other things too. Will use it one day to clean up the Vivillon quest line

2022-06-24 22:21 UTC, RedSparr0w commented on src/scripts/quests/questTypes/CaptureSpecificPokemonQuest.ts
> +        return this.customDescription ?? `Capture ${this.pokemon.name} Pokémon.`;
Could we also make use of the `capturesNeeded` variable here (in case it is more than 1)?

2022-06-24 22:21 UTC, RedSparr0w requested changes
PR looks good,
Could you please also update the questlines where we require capturing a specific Pokémon to make use of this too?

2022-06-25 06:07 UTC, Jaaslet commented
Should have fixed both of your comments now. The Vivillon hunt was the only one i could find, which could use the new quest.
I also removed 'Pokemon' from the description, because it seemed redundant

2022-07-10 17:55 UTC, Aegyo approved these changes

2022-07-10 18:03 UTC, merged