WIP | feat(hatchery): allow eggs and fossils in queue
pokeclicker/pokeclicker pull request #2433
Opened 2022-06-12 22:12 UTC by shallotmama

Adds the ability to put eggs and fossils in the queue.

Still need to test it out more thoroughly, but from what I've seen so far it does what it should.

Closes #1362

2022-06-12 23:05 UTC, shallotmama commented
![image](https://user-images.githubusercontent.com/54243859/173257214-1c2c1e54-414b-4395-ad10-9d5077dec668.png)

2022-06-13 17:40 UTC, Jaaslet commented
(Have not tested it yet. Just took a quick look)
The breeding window still has both the "full queue" and "no empty slots" warning. I don't think there are any situations anymore, that only cares about empty slots? So we should remove that.
And the implementation looks cool! It's how i would had made it, if i ever found time to do it.

2022-06-15 05:42 UTC, Jaaslet requested changes
HatcheryQueueEntry.ts seams a bit overcomplicated, which makes the code hard to understand (and hard for me to review the PR).
Can it be changed to an abstract class, with a child-class for each of the 3 types?
Then it can also contain stuff like how to find the image and how to add/remove it from queue, to make the html look nicer.

2022-06-16 20:56 UTC, shallotmama commented
The three types are all string literal union types pulled from enums, so they don't make sense as their own classes. I did a little cleanup though, and I think it's a lot clearer now.

The main complication was that `EggItemType` and the image files use the format of `<type>_egg` while everything else just uses the type name. I don't know why I was doing the weird conversions instead of just doing it the way it is now. 😆

2022-06-16 22:18 UTC, shallotmama commented on src/modules/pokemons/PokemonNameType.ts
> +export const pokemonNameList = ['Bulbasaur',
I changed this to allow for a safe type guard on `PokemonNameType` using the pattern found here: https://stackoverflow.com/questions/36836011/checking-validity-of-string-literal-union-type-at-runtime

If this is an unwanted change, let me know, and I can go back to using the unsafe type guard (which just checked if it wasn't an `EggNameType` or `FossilNameType`).

2022-11-06 17:41 UTC, Aegyo commented
This PR has gotten a bit stale and collected a bunch of conflicts (our fault, sorry about that), I'm going to close this one and if you are still interested in doing this you can redo/rebase your current work over the latest develop and open a new PR.

2022-11-06 17:41 UTC, closed without merging