Add player sprite to current location
pokeclicker/pokeclicker pull request #2552
Opened 2022-06-30 17:45 UTC by Dragonchitos

The player sprite from profile indicates the current position. It works for routes, town, dungeon and overlay related to dungeon (like distortion world). 
The green background that indicated the position is removed, so we can see the state of the current location (route or dungeon) more easily.
I didn't test for Alola because I don't have a save in Alola yet.

2022-06-30 20:55 UTC, Jaaslet requested changes
I LOVE IT! It looks cool. But i still have some comments for you :)
- Some places, i am seeing double
  - MeleMele sea
  - Relic Passage
  - Dark cave
  - Diglett's Cave
- Mega dungeons (like Mt. Chimney) does not show the icon, when you enter it

2022-06-30 20:55 UTC, Jaaslet commented on src/templates/mapOverlay.ejs
> +    - moveToTown : Optional : String
Not really a "moveToTown". That kinda indicates a clickaction. Let's call it something like "connectedToTown" or something

2022-06-30 20:55 UTC, Jaaslet commented on src/templates/mapDungeon.ejs
> +    - notMain : Optional : Boolean
Let's call it "isExtension" to match our comments in the SVGs

2022-06-30 20:55 UTC, Jaaslet commented on src/components/AlolaSVG.html
> +            , width: 1, height: 7, notMain: true
Let's move all the notMain to a new line. You are renaming them anyways :)

2022-06-30 22:04 UTC, Dragonchitos commented on src/styles/variables.less
> +@questAtLocation: #ff0033;
I don't know how to do that. Where should i put the function ?

2022-07-01 02:04 UTC, Jaaslet commented on src/styles/variables.less
> +@questAtLocation: #ff0033;
Update.ts

2022-07-01 08:36 UTC, silverwolf2000 commented on src/scripts/worldmap/MapHelper.ts
> +        if (player.route() == route && player.region == region) {
```suggestion
        return (player.route() == route && player.region == region)
```

2022-07-01 23:08 UTC, Dragonchitos commented
So : 
 - I did all the rename and move things
 - I add the update function
 - I think I fix Melemele sea, not sure for this one
 - I fix "mega dungeon", which are actually town with several dungeons related without own icon

For Relic Passage, Dark cave and Diglett's Cave : they have two separated icons, so I think it's weird to have the player icon only in one. The player may be confused to click on dungeon and not see the player icon appear, but see it in another place. But I know it's also weird to see two player icons, so I don't know which solution is best.

2022-07-02 08:07 UTC, Jaaslet approved these changes
I have fixed the update function and changed the quest default color to the old current location color.
The rest looks good. Thanks for the PR!

2022-07-02 08:08 UTC, merged

2022-07-02 08:21 UTC, Jaaslet commented
> For Relic Passage, Dark cave and Diglett's Cave : they have two separated icons, so I think it's weird to have the player icon only in one. The player may be confused to click on dungeon and not see the player icon appear, but see it in another place. But I know it's also weird to see two player icons, so I don't know which solution is best.

I think two icons is the best solution, so we are keeping that one. We can always change it later, if someone has a good argument.