Added pokerus filter to breeding window
pokeclicker/pokeclicker pull request #2563
Opened 2022-07-02 09:00 UTC by Jaaslet

![image](https://user-images.githubusercontent.com/2961347/176993982-9d0aa846-0f2f-45fb-8ae5-e0d134b983ea.png)

2022-07-02 15:48 UTC, Aegyo requested changes
Minor text gripe, otherwise perfectly fine :+1:

2022-07-02 15:48 UTC, Aegyo commented on src/components/breedingModal.html
> +                                <label>Pokerus Status</label>
```suggestion
                                <label>Pokérus Status</label>
```

2022-07-02 15:50 UTC, Aegyo commented
Do we want a Pokérus sort option too?

2022-07-02 16:10 UTC, Jaaslet commented
> Do we want a Pokérus sort option too?

No idea. Personally, i can't see a use case, when people have the filter, so my plan is to leave it out, until someone gives me a good reason

2022-07-02 16:13 UTC, Qwertypop04 commented
> No idea. Personally, i can't see a use case, when people have the filter, so my plan is to leave it out, until someone gives me a good reason

Would a sort for number of EVs be more useful, maybe?

2022-07-02 16:19 UTC, Jaaslet commented
> Would a sort for number of EVs be more useful, maybe?

Yeah, that would make more sense. Yeah, i will add it tomorrow. A sort option does not take up any UI space, so might as well

2022-07-02 17:28 UTC, CorgiOnNeptune commented
A Display Value for EVs would also be a useful addition.

2022-07-03 07:42 UTC, Jaaslet commented
I have added sorting option and display now. So it should be ready for review again.

2022-07-03 21:23 UTC, Aegyo approved these changes
#2574 will need a change updating how evs are calculated for the display and sort option, but everything seems to work here :+1:

2022-07-04 06:38 UTC, Jaaslet commented
> #2574 will need a change updating how evs are calculated for the display and sort option, but everything seems to work here 👍

I will then merge this one, so i can fix it in the other PR

2022-07-04 06:40 UTC, merged