Move EVs from statistics
pokeclicker/pokeclicker pull request #2574
Opened 2022-07-03 10:08 UTC by Jaaslet

EVs should be saved on PartyPokemon and not in statistics. This should also fix the problem people have with EVs multiplier not showing up everywhere we want it to

2022-07-03 21:01 UTC, Aegyo requested changes
Couple of comments, works fine otherwise from what I can see :+1:

2022-07-03 21:33 UTC, Aegyo commented on src/scripts/Update.ts
> +                p[9] = saveData.statistics.effortPoints[p.id];
For saves before effortPoints was added:
```suggestion
                p[9] = saveData.statistics.effortPoints?.[p.id] || 0;
```

2022-07-04 07:11 UTC, Jaaslet commented
I have merged this with the filters and fixed it. I have resolved all your comments. It's ready for review again :)

2022-07-04 22:41 UTC, Aegyo approved these changes

2022-07-05 05:52 UTC, merged