Tutorial overhaul
pokeclicker/pokeclicker pull request #2592
Opened 2022-07-06 21:14 UTC by Ultima1990

Changes to the tutorial quests.
Now requires talking to 2 NPCs:
Mom, who recommends talking to NPCs. An important lesson for players I think.
Old Man, who explains the ball selector.
Also now requires catching 5 Pidgey. The player now has to prove that they understand the ball selector. RIP monotype.

No more How Blu!

2022-07-08 17:40 UTC, Jaaslet requested changes
It looks good. I did not find a way to break the tutorial. I just have one small comment.

2022-07-08 17:40 UTC, Jaaslet commented on src/scripts/quests/QuestLineHelper.ts
> +        const talkToOldMan = new TalkToNPCQuest(ViridianCityOldMan2, 'Talk to the Old Man in Viridian City to learn about catching. Talk to the Old Man again if you need a reminder.', OldManReward);
"Talk to the Old Man again if you need a reminder."
It seems confusing that it's a part of the quest text. It kinda looks like it's relevant for the quest. And the old man is already saying something like that.

2022-07-08 23:57 UTC, xslk commented
What if, to save monotype challenges, you change the quest to a 2 part. 

Instead of catch 5 Pidgeys he just ask to catch 5 pokemon. You return to him and then he says something like "did you noticed your dungeon tokens increasing after each catch? Oh you didn't? Catch 5 more pokemon and pay attention to the number this time."

2022-07-09 00:13 UTC, Ultima1990 commented
> What if, to save monotype challenges, you change the quest to a 2 part.
> 
> Instead of catch 5 Pidgeys he just ask to catch 5 pokemon. You return to him and then he says something like "did you noticed your dungeon tokens increasing after each catch? Oh you didn't? Catch 5 more pokemon and pay attention to the number this time."

No can do. The catch 5 Pidgey quest is intended to force the player to use the ball selector and set a ball to Caught. If they can just catch any 5 mons it's possible that they won't need to do this.

2022-07-09 21:57 UTC, Jaaslet approved these changes
It works now, and i think it's more helpful. Let's release it, and see if it stops some of the questions.
Thanks for the PR

2022-07-09 21:57 UTC, merged