Alternate forms ordered in official pokedex listing
pokeclicker/pokeclicker pull request #3340
Opened 2022-11-09 10:03 UTC by osherwott

Switched order of forms in PokemonList.ts and PokemonNameTypes.ts to accurately reflect official and game listings:
* Pikachu (World Cap) between (Partner) and (Flying)
* Vivillon (Icy Snow) as 666.00, (Meadow) as 666.06, and (Poké Ball) as 666.18
* Flabébé, Floette, and Florges (Orange) between (Yellow) and (Blue)
* Minior in *ROGBIV* order: (Red), (Orange), (Yellow), (Green), (Blue), (Indigo), (Violet)
* Alcremie by cream: (Vanilla), (Ruby Cream), (Matcha), (Mint), (Lemon), (Salted), (Ruby Swirl), (Caramel), (Rainbow), and within each cream subdivided by sweet: (Strawberry), (Berry), (Love), (Star), (Clover), (Flower), (Ribbon); ID subdivisions to two decimal places changed accordingly

Re-named files of images (shiny and non-shiny) to match new IDs:
* Pikachu 25.08 - 25.12
* Vivillon 666 - 666.18
* Flabébé 669.02 and 669.03
* Floette 670.02 and 670.03
* Florges 671.02 and 671.03
* Minior 774.01 - 774.07
* Alcremie 869.01 - 869.86 (tenths and hundredths numbers changed accordingly)

Re-added Pumpkaboo (Average) non-shiny sprite that had been omitted for some time after being replaced with Pumpkaboo (Small)

Adjusted code in PokedexHelper.ts to account for Vivillon (Meadow)'s new ID

2022-11-09 10:30 UTC, Farboo171 commented
There are a LOT of things that would need to be checked for dependency from this change. Any file that references an alt form (from quests immediately comes to mind) by number would be affected.

2022-11-09 10:36 UTC, osherwott commented
I figured that'd be the case. Would you know where the code for individual quests is located? I was not able to see any specific quests in the files I found.

2022-11-09 10:50 UTC, Farboo171 commented
https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/quests/QuestLineHelper.ts

And I am sure there are other places that have dependencies that I don't know about.

Checking all the dependencies for all the Pokedex numbers AND writing the correct Update functions is a massive undertaking, probably best split into a few PRs. Maybe one per mon. And if you ask around in the discord , other people more familiar with other parts of the code can probably give more details on places to check

2022-11-09 11:06 UTC, osherwott commented
Thank you. As of now I haven't noticed any issues, it seems that all the forms I reordered use their names as reference instead of ID. I have checked QuestLineHelper.ts, Farming.ts, Discord.ts, and BattleCafe.ts. Are there any other dependencies other than obtain methods I should be aware of?

2022-11-09 11:24 UTC, Jaaslet commented
This will need an update function. We changed the id of the event mons in like version 9, so you can look there

2022-11-09 12:38 UTC, Aegyo commented
Can you keep this PR to only your flabebe, floette, florges, and minior changes please? The others are being changed around already and this conflicts with some decisions there.

Your update function will need to update the id for pokemon in the party list, and move statistics to their new id as well. Looks like this was done in [0.9.0](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/Update.ts#L598), but there are more statistics to move now - check PokemonHelper.incrementPokemonStatistics

Might be easier to just open a new PR with just the requested pokemon, but I'll leave that decision to you.

2022-11-09 13:00 UTC, osherwott commented
Thanks for the information Aegyo. I'll check over the new statistics and figure out what to do with my PR later. If you don't mind me asking, is there anything I could do for the other forms since I'm already working on this? Ideally I would like to help any way I can, but understand if you'd rather work on it yourselves.

2022-11-09 13:22 UTC, Aegyo commented
I think the best thing you can do to help would be making your update function a generic static property on Update, like moveIndex and changeHatcheryKey are.

I would call it something like `rotatePokemonIds` and have it take a list of ids that need rotating around.
eg it looks like minior has these rotations `[774.01, 774.05]` `[774.02, 774.04]` `[774.03, 774.06, 774.07]`

2022-11-09 13:59 UTC, PixLSteam commented
> I think the best thing you can do to help would be making your update function a generic static property on Update, like moveIndex and changeHatcheryKey are.
> 
> I would call it something like `rotatePokemonIds` and have it take a list of ids that need rotating around. eg it looks like minior has these rotations `[774.01, 774.05]` `[774.02, 774.04]` `[774.03, 774.06, 774.07]`

When doing stuff like that, we have to be careful not to introduce a potential bug in future versions. For example, data model changes could easily break older update scripts if they rely on a static method.

2022-11-09 14:09 UTC, Aegyo commented
I think for this it should be fine? If the save data model changes, then we would just need to change the name to `xxxPre0_10_24` (or whatever version) and have a new version to work with the latest data model?

Or am I missing something?

Maybe all of these static functions should be versioned from the start to save effort later, but that can be handled separately

2022-11-09 14:17 UTC, PixLSteam commented
I think it should be fine for this as long as we ignore missing statistics. We should probably rename older helpers whenever we change the model, but I'm pretty sure we'd just forget about that so there's no point.

Also, we gotta make sure the rotation works properly. I can't test the current update function but I feel like we'd erase/overwrite a few statistics with what we have right now.

2022-11-12 00:29 UTC, osherwott commented
I'm afraid I'm having difficulty with arrays. I'm not sure how to make the function account for different row lengths, nor if I should differentiate the existing function from 0.9.0 in some way. I'm not experienced with coding so this is more of a hobby and it will take me a while to figure out. I will study the existing code and online in the meanwhile. Any help is appreciated @Aegyo

2022-11-12 00:35 UTC, Qwertypop04 commented
When you removed the changes to images you removed the image changes for Pokémon that are still changing, as well.

2022-11-12 00:43 UTC, osherwott commented
Don't worry, I'm aware of that! I have prioritized on the function, but will remember to address the other file changes before the PR is finalized!

2022-11-12 00:44 UTC, PixLSteam commented
> I'm afraid I'm having difficulty with arrays. I'm not sure how to make the function account for different row lengths, nor if I should differentiate the existing function from 0.9.0 in some way. I'm not experienced with coding so this is more of a hobby and it will take me a while to figure out. I will study the existing code and online in the meanwhile. Any help is appreciated

Maybe something like this:

```js
const obj = {
	a: 1,
	b: 2,
	c: 3,
	d: 4,
	e: 5,
	f: 6
};
function rotate(rotations) {
	const firstValue = obj[rotations[0]];
	for (let i = 0; i < rotations.length - 1; i++) {
		obj[rotations[i]] = obj[rotations[i + 1]];
	}
	obj[rotations[rotations.length - 1]] = firstValue;
}
```
Keep in mind that this is just a POC and you'd have to figure out how to do this with all of the relevant statistics as well as the PartyPokemon data.

2022-11-12 01:01 UTC, Aegyo commented
> if I should differentiate the existing function from 0.9.0
This should be different, because you are moving pokemon around into existing IDs, and won't need to delete their previous id locations (because something else will overwrite there anyway)
The one in 0.9.0 is removing an old id and creating a new one for the data to live in.

2022-11-14 10:55 UTC, osherwott commented
Also could this please be marked as a Draft. Thanks

2022-11-14 23:06 UTC, Aegyo commented
> Help is needed

What kind of help would you like? We can suggest more code (either the whole thing or for a particular issue you are having), or someone can push changes directly to your pr branch for you to us.

2022-11-15 10:53 UTC, osherwott commented
Sorry for the late reply, it turned out the if statements from the copied 0.9.0 function was messing with the function. I believe it should be error free now, however it does not appear to be working. I will change the image and list files for now and go over the function later. Any review or pushes by others would be appreciated in the meanwhile. Thanks

2022-11-15 14:10 UTC, Aegyo commented on src/scripts/Update.ts
> +            Update.rotatePokemonIDs(saveData, formIDs);
Had a quick look through, your rotatePokemonIDs looks fine, but this line I think should be:
```ts
        formIDs.forEach((list) => Update.rotatePokemonIDs(saveData, list));
```

On mobile so I can't test it out right now though.

2022-11-16 01:01 UTC, osherwott commented
I've been trying with a save file for hours and it doesn't work. If your dummy data went through then I have no idea why it won't work on the game itself. Upon further testing it seems that I can't even overwrite any data at all. I hope you are having better luck.

2022-11-16 01:07 UTC, Aegyo commented
Looks like we've put the update in the v0.10.1 section, try moving it over to the v0.10.2 bit and load a save that hasn't been on v0.10.2 yet :sweat_smile:

2022-11-16 01:22 UTC, osherwott commented
I just noticed you moved the statistics in #3374, could that be affecting it?

2022-11-16 01:24 UTC, Aegyo commented
I don't think so, but I'm looking into it now

2022-11-16 01:37 UTC, Aegyo commented
Had some capitalization errors, seems to work with an actual save file after fixing those and moving into the v0.10.2 section.
Do you want me to sort out the conflicts too?

2022-11-16 02:05 UTC, osherwott commented
> Had some capitalization errors
Does this mean the original 0.9.0 function should be rewritten with capital letters as well? It might not work currently, and it'd be best for posterity.
> Do you want me to sort out the conflicts too?
Yes please, and thank you!

Also PixLSteam mentioned PartyPokemon data. I suppose this means held items, nicknames, and the like. I'm not sure how to include these in this function, since there wasn't such code in the 0.9.0 one. I want to avoid causing any bugs with this function if used in the future, especially since mega stones are being currently implemented.

2022-11-16 02:15 UTC, PixLSteam commented
All the data directly associated with the PartyPokemon should be copied over since we just change the id property - even if we add new properties in the future.

2022-11-16 02:33 UTC, osherwott commented
It works!

2022-11-16 02:35 UTC, osherwott commented
Oh, but before it's merged, can I rotate the Vivillon? #3371 didn't put Poke Ball pattern towards the end

2022-11-16 03:06 UTC, osherwott commented
Ready to merge!

2022-11-16 18:46 UTC, osherwott commented
Also @Aegyo should I make a new PR for a "move" function? Now that we have this working we can trim it down and add "delete old statistics" to help Qwertypop04 move all those IDs in #3371

2022-11-16 18:51 UTC, Aegyo commented
No need imo, it can be handled in Qwerty's PR

2022-11-17 08:50 UTC, Jaaslet requested changes
Some of the images have been changed in the docs folder instead of the src folder. All changes should be in the src folder.
It's a bit hard for me to test when the images are wrong, so i will test the rest, when that has been fixed :)

2022-11-18 01:51 UTC, Aegyo commented
@osherwott do you think you can get those images sorted in the next 6-ish hours, before Jaaslet comes back for another review?

Non-shiny images for 669, 670, 671, and 774 variants were made in the docs folder instead of src.
Also looks like 666.10 didn't get an image update, but it is in the rotation list. The image would be named 666.1.png, since that 666.10 is treated as a number and loses the trailing 0.

2022-11-18 03:04 UTC, osherwott commented
Sorry for the delay! Everything should be fine now.

2022-11-18 03:08 UTC, Aegyo commented
Image updates for 666.10 still missing, unless I'm being blind again :sweat_smile:

2022-11-18 03:20 UTC, osherwott commented
What a headache! _NOW_ everything should be fine!

2022-11-18 03:31 UTC, Aegyo commented
Looks ok to me too, hopefully Jaaslet agrees :crossed_fingers:

2022-11-18 07:39 UTC, Jaaslet approved these changes
Looks good. Thanks for the PR

2022-11-18 07:40 UTC, merged