Can now set pokemon party nickname
pokeclicker/pokeclicker pull request #3348
Opened 2022-11-10 21:33 UTC by Jaaslet

Nicknames! nincknames! come and set your nicknames!

You can change it in the pokedex window (like with gender and shiny), and it should only show up in the areas that is related to your own pokemon.
I have piggybacked a lot off the translation project.

Pokedex window looks weird, i know. But i did not really know how to make it better, and players won't use it very often

2022-11-10 23:33 UTC, Aegyo commented
Something that translations also didn't do, but I think name sorting should work off the name we are displaying, currently it uses the english name. [link to code](https://github.com/pokeclicker/pokeclicker/blob/2c1ba76c47b0b4a02af475b27697ac3c368a9aaf/src/modules/settings/SortOptions.ts#L39)

2022-11-10 23:37 UTC, Aegyo approved these changes
Approved other than the comment above, you can either fix that here or we can handle it separately

2022-11-10 23:44 UTC, Aegyo commented
Oh actually looks like someone had done some work on this same thing in #2737 / #2707 - the name input there is above the table so you have more control over the width, seems better than what you have now. Steal that bit?

2022-11-10 23:45 UTC, Aegyo requested changes
Requesting above change(s)

2022-11-11 00:44 UTC, Crobat4 commented
If you put a special character in the nickname, the game won't save.
![image](https://user-images.githubusercontent.com/104547700/201235509-0f8e56b4-7543-496f-a7a9-9109e149f908.png)

2022-11-11 07:26 UTC, Jaaslet commented
> Oh actually looks like someone had done some work on this same thing in #2737 / #2707 - the name input there is above the table so you have more control over the width, seems better than what you have now. Steal that bit?

I think Corgi already moved the name up there like a couple of weeks ago?

2022-11-11 07:39 UTC, Jaaslet commented
I have also fixed the encoding problem, the sorting problem and made the display look nicer

2022-11-11 18:54 UTC, Aegyo requested changes
Small change requested, everything else looks fixed to me :+1:

2022-11-11 18:54 UTC, Aegyo commented on src/components/pokemonStatisticsModal.html
> +                        <td colspan="2" class="text-left align-middle">Party Nickname</td>
I think it looks a little better with this text centered
```suggestion
                        <td colspan="2" class="text-middle align-middle">Party Nickname</td>
```

2022-11-11 19:00 UTC, Aegyo approved these changes

2022-11-11 19:02 UTC, merged