dream orb notifications shows up after animation
pokeclicker/pokeclicker pull request #3399
Opened 2022-11-16 09:31 UTC by Jaaslet

The notification showed up when the animation started, so i moved code around.

2022-11-17 00:23 UTC, Aegyo requested changes
It is possible to start opening on one orb type, and then switch to another (that you possibly have <= 0 of) and get an item from that one instead.

Should probably leave the incrementObservable and item rolling outside of the timeout.

2022-11-17 00:25 UTC, Aegyo commented
or if that is a problem, keeping a note of the orb used and reference that instead if this.selectedOrb()

2022-11-17 09:03 UTC, Jaaslet commented
I did the 2nd solution

2022-11-18 00:20 UTC, Aegyo approved these changes

2022-11-18 00:21 UTC, merged