Removes more repeated Pokemon from routes
pokeclicker/pokeclicker pull request #3453
Opened 2022-11-22 20:46 UTC by osherwott

* Poliwag from Johto Route 31 water
* Wingull from Sinnoh Route 213 water
* Dunsparce from Kalos Route 3 land
* Machoke from South Lake Miloch weather (Overcast, Snow, Blizzard, Sunny, and Sandstorm)
* Tyrogue from South Lake Miloch weather (Overcast)
* Drifloon from South Lake Miloch weather (Fog)
* Pyukumuku from South Lake Miloch weather (Thunderstorm)
* Jellicent from Lake of Outrage Thunderstorm
* Mareanie from Motostoke Riverbank weather (Thunderstorm)
* Hawlucha from Hammerlocke Hills weather (Overcast)
* Greedent from Giant's Bed weather (Blizzard)
* Beartic from Frigid Sea Blizzard
* Skwovet from Ballimere Lake land

2022-11-22 20:49 UTC, osherwott commented
Forgot to link to/mention #3351

2022-11-22 21:04 UTC, xslk commented
Weather pokemon are deliberate

2022-11-22 21:08 UTC, Qwertypop04 commented
> Weather pokemon are deliberate 

They are not deliberate

2022-11-22 21:13 UTC, osherwott commented
Noted and fixed

2022-11-22 21:19 UTC, osherwott commented
Should any edits be needed, feel free to do so. The "Allow edits by maintainers" box is ticked.

2022-11-22 21:22 UTC, Qwertypop04 commented
> Noted and fixed

SLK was incorrect, the repeats on weather routes were not intentional.

2022-11-22 21:26 UTC, xslk commented
Qwerty cleared it up. Mobile view = L

2022-11-22 21:26 UTC, osherwott commented
Noted and fixed... again!

2022-11-23 21:28 UTC, Jaaslet approved these changes
I found two places where it looks like it was not a duplicate (or i am blind). But other than that, it looks good

2022-11-23 21:28 UTC, Jaaslet commented on src/scripts/wildBattle/RouteData.ts
> +        land: ['Boltund', 'Audino', 'Yamper', 'Mime Jr.', 'Aron'],
This looks like a mistake?

2022-11-23 21:28 UTC, Jaaslet commented on src/scripts/wildBattle/RouteData.ts
> +          new SpecialRoutePokemon(['Snorunt', 'Cryogonal', 'Vanillish', 'Absol', 'Vanillite', 'Glalie', 'Froslass', 'Glaceon', 'Nidoking', 'Nidoqueen', 'Vanilluxe', 'Snorlax'],  new WeatherRequiremen
This looks like a mistake?

2022-11-23 21:29 UTC, Jaaslet requested changes
Approved by mistake...

2022-11-23 21:32 UTC, Jaaslet approved these changes
Someone pointed out the mons i thought was a mistake is below special, in the headbutt section...
Thanks for the PR!

2022-11-23 21:36 UTC, merged