Fix: Real Evolution challenge exploit by evolving a pokémon in the hatchery
pokeclicker/pokeclicker pull request #3821
Opened 2023-01-20 13:30 UTC by Alderi-Tokori

Fixes issue #3444. If the real evolution challenge is active, you can't use a stone on Pokémons in the hatchery.

2023-01-20 13:36 UTC, PixLSteam requested changes
Just some small text/comment changes. Looks good otherwise, but I haven't actually tested it.

2023-01-20 13:36 UTC, PixLSteam commented on src/modules/items/ItemHandler.ts
> +            // If the real evolution challenge is active, we prevent using stones on pokemons in the hatchery to prevent exploits
```suggestion
            // If the real evolution challenge is active, we prevent using stones on Pokémon in the hatchery to prevent exploits
```

2023-01-20 13:36 UTC, PixLSteam commented on src/modules/items/ItemHandler.ts
> +                message: 'You can\'t use a stone on a Pokémon if it\'s in the hatchery...',
```suggestion
                message: 'You can\'t use an evolution item on a Pokémon if it\'s in the hatchery...',
```
I believe we refer to all evolution items as stones internally but there are other kinds of evolution items and this message could be confusing.

2023-01-20 13:37 UTC, Razikd29 commented
Maybe it's a bit too late to ask about that topic, but shouldn't that be a generic behaviour ? Working in a similar fashion as for vitamins that you can't give if the Pokémon is in the hatchery ?

2023-01-20 13:38 UTC, PixLSteam commented
Vitamins mess with the Pokémon's step count. Evolving the Pokémon does not actually have any effects on the prevolution outside of this challenge, so it should be fine.

2023-01-20 13:41 UTC, Razikd29 commented
It was more about making the item behaviour consistent through all scenarios. But I guess it is fine, as you say

2023-01-20 14:01 UTC, Alderi-Tokori commented
> Just some small text/comment changes. Looks good otherwise, but I haven't actually tested it.

Committed the suggested changes.

2023-01-21 00:57 UTC, Aegyo approved these changes

2023-01-21 00:59 UTC, merged