Added new quest in Kanto for Bill's Grandpa
pokeclicker/pokeclicker pull request #3823
Opened 2023-01-20 18:50 UTC by LuchoDreamer

This quest is to help alleviate the QP wall from Kanto described in the #1071 approved suggestion.

This PR consists of several things:

Kanto map:

1. Adds Bill's House in Kanto (I was surprised that this place was never in the game to start with). It doesn't mess with Suicune's sprite during its quest. This house will be used for the whole quest.
2. Fixes a small cut of top of a tree that shouldn't be there next to Mt Moon. Mentioned by Vodo in discord.

Sprites:

1. Two Bill's Grandpa sprites made by courtesy of Drakay

Quest:

1. The quest consists, in its majority, of a pokémon treasure hunt based on both gen 2 and its remakes in gen 4, where if you present specific pokémon to Bill's Grandpa in the order that he asks them for, he will reward you each time with a evolution stone.
2. Majority of the quests consist of catching the specific pokémon (with a hint, not said outright), and defeating 100 pokémon of that same type to add a little bit of extra difficulty/time to it.
3. Most of these pokémon are the same he asks for during the game, one of them is actually a gen 2 pokémon, so I changed ir for a gen 1 pokémon, and another one of them is changed because it's a QP pokémon and it would kinda defeat the purpose of the quest.
4. As said at the start, this quest is aimed to lessen the QP wall in Kanto, thus this whole quest has a value of 16500 QP, but it's not 16500 QP as reward, the rewards are evo items/pokémon with that value in total (keeping it a bit vague to not destroy the surprise, but it's probably easy enough to guess to be honest).
5. This quest also aims at keeping you busy for most of Kanto with it. You unlock it when you get access to Bill's House (after route 25, pretty early), and you can get its first two parts done pretty fast, the third part requires either after Koga or an egg (and as far as I know new players don't focus on eggs until much later on). And after two more parts, it ends with a temporary battle, that is balanced with Giovanni's gym in mind (Around 5% stronger than Giovanni).
6. Every step of the quest gives you one different reward.
7. After the quest is done, Bill's Grandpa remains in the house, house-sitting, so it's not empty.

This is all, if the rewards are too much, I can rebalance them, but I really think these rewards are fair since the quest keeps you occupied during most of the Kanto journey.

I hope the quest is liked o/.

2023-01-20 20:26 UTC, zyx-xyzzy commented on src/scripts/quests/QuestLineHelper.ts
> +        ],'Bill\'s Grandpa want you to catch a Pokémon that is pink and like a balloon.'));
want -> wants

2023-01-20 20:26 UTC, zyx-xyzzy commented on src/scripts/quests/QuestLineHelper.ts
> +        ],'Bill\'s Grandpa want you to catch a Pokémon that is round, blue and has has leaves growing on its head'));
add comma after “blue”

2023-01-20 20:27 UTC, zyx-xyzzy commented on src/scripts/quests/QuestLineHelper.ts
> +        ],'Bill\'s Grandpa want you to catch a Pokémon that is has a red sphere in its body and is shaped like a star'));
want -> wants
is has -> has

2023-01-20 20:28 UTC, zyx-xyzzy commented on src/scripts/quests/QuestLineHelper.ts
> +        ],'Bill\'s Grandpa want you to catch a Pokémon that is very loyal and supposedly roars pretty well'));
want -> wants

2023-01-20 20:28 UTC, zyx-xyzzy commented on src/scripts/quests/QuestLineHelper.ts
> +        ],'Bill\'s Grandpa want you to catch a Pokémon that has a yellow body and red cheeks'));
want -> wants

2023-01-20 20:30 UTC, zyx-xyzzy commented on src/scripts/towns/TownList.ts
> +    'Ah, my grandson mentioned a round, green Pokémon, wait not green, it\'s blue, a blue Pokémon that has leaves growing on its head',
Missing punctuation at the end of the sentence
(note: this also applies to several of the quest-step descriptions, but idk if those are intentional or not…)

2023-01-20 20:31 UTC, zyx-xyzzy commented on src/scripts/towns/TownList.ts
> +    'Ah, you brought it to me. Staryu is the name, you said? It\'s certainly shaped like a star. You are so kind for coming back with it.! This Water Stone should be really useful to you.',
.! -> !
(in the third sentence)

2023-01-20 20:32 UTC, zyx-xyzzy commented on src/scripts/towns/TownList.ts
> +    'I was thinking, Bill told me about a Pokémon that is very loyal to its trainer. It\'s supposed to roar well',
missing punctuation at the end of the sentence, again

2023-01-20 20:32 UTC, zyx-xyzzy commented on src/scripts/towns/TownList.ts
> +    'I would really want to meet it, can you stop by when you meet one, please?',
would really want to -> either “would really like to” or “really want to”

2023-01-20 20:33 UTC, zyx-xyzzy commented on src/scripts/towns/TownList.ts
> +    'Ah, so this little puppy is Growlithe? I cannot beging to imagine its roaring! I\'m so happy that you are doing all this for me. Thank you so much! I was saving this Fire Stone for a rainy day,
beging -> begin

2023-01-20 20:34 UTC, zyx-xyzzy commented on src/scripts/towns/TownList.ts
> +    'This the one I\'m most excited to meet, so please, once you catch it come back, I will have tea prepared for you',
once you catch it come back -> come back once you catch it
missing punctuation at the end of the last sentence

2023-01-20 20:36 UTC, zyx-xyzzy commented on src/scripts/towns/TownList.ts
> +    'Let me tell you though, in my youth I was strong enough to beat Viridian City\'s Gym, so don\'t expect me to be a pushover',
one last “missing punctuation at the end of the sentence”
(btw, apologies to discord readers if all these notes clog the update channel, orz)

2023-01-20 20:39 UTC, LuchoDreamer commented
Thank you zyx-xyzzy for going through all the dialogue and telling me the mistakes. I should have fixed them all, even one that you missed, and the punctuation during quests that you were unsure if it was intentional (it was not).

Thanks again!

2023-01-21 03:34 UTC, Farboo171 reviewed
Just some text change comments

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/quests/QuestLineHelper.ts
> +        const talkToBillsGrandpa3 = new TalkToNPCQuest(BillsGrandpa3, 'Show your Oddish back to Bill\'s Grandpa.', LeafStoneReward);
Same phrasing comment as Jigglypuff

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/towns/TownList.ts
> +    'When you happen to get one, would you like to come back here so I can see it, please?',
Awkward phrasing. Maybe something like "When you get one, could you come back here so I can see it, please?" for the last line

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/quests/QuestLineHelper.ts
> +        const talkToBillsGrandpa4 = new TalkToNPCQuest(BillsGrandpa4, 'Show your Staryu back to Bill\'s Grandpa.', WaterStoneReward);
Same comment as Jigglypuff step

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/towns/TownList.ts
> +    'I would really like to meet it, can you stop by when you meet one, please?',
Awkward phrasing. Maybe something like "I would really like to meet one, can you stop by if you capture one?" for the last line

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/quests/QuestLineHelper.ts
> +        const talkToBillsGrandpa5 = new TalkToNPCQuest(BillsGrandpa5, 'Show your Growlithe back to Bill\'s Grandpa.', WaterStoneReward);
Same comment as Jigglypuff

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/towns/TownList.ts
> +    'This the one I\'m most excited to meet, so please, come back once you catch it, I will have tea prepared for you.',
"This the one I\'m most excited to meet Please come back once you catch it, I will have tea prepared for you.'
Lots of commas

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/quests/QuestLineHelper.ts
> +        const talkToBillsGrandpa6 = new TalkToNPCQuest(BillsGrandpa6, 'Show your Pikachu back to Bill\'s Grandpa.', ThunderStoneReward);
Same comment as Jigglypuff step

2023-01-21 03:34 UTC, Farboo171 commented on src/scripts/towns/TownList.ts
> +    'There is someone I would like to go with you, my partner Eevee.',
"There is someone I would like to go with you: my partner Eevee."

2023-01-21 12:18 UTC, LuchoDreamer commented
Thanks for correcting the phrasing! In some places I was struggling trying to get a different wording for every time the old man asks you for a different poke. So some of them got a little bit too convoluted and unnecessary.

2023-01-22 15:12 UTC, Vodovik commented
tested it, works well : )

2023-01-28 19:20 UTC, Aegyo commented on src/scripts/temporaryBattle/TemporaryBattleList.ts
> +    ],
Is this intentionally ~50% tougher than the champion fight?

2023-01-28 19:21 UTC, LuchoDreamer commented
Is it 50% tougher than Champion? I gave it 5% more hp than Giovanni. The battle is 60 seconds, not 30 seconds.

2023-01-28 19:22 UTC, Aegyo commented
I always forget that temp battles are longer, my bad

2023-01-28 19:34 UTC, Aegyo approved these changes

2023-01-28 19:35 UTC, Aegyo requested changes
Just the update function needs to be moved, everything else looks fine :+1:

2023-01-28 19:35 UTC, Aegyo commented on src/scripts/Update.ts
> +            saveData.statistics.temporaryBattleDefeated = Update.moveIndex(saveData.statistics.temporaryBattleDefeated, 12);
Needs to be moved into a 0.10.10 update functions

2023-01-28 19:52 UTC, LuchoDreamer commented
Perfect, it's done.

2023-01-29 18:42 UTC, Aegyo approved these changes

2023-01-29 18:49 UTC, merged

2023-05-23 20:00 UTC, Darckclow commented
Hi,
The quest is bugged. I'm at the part where I have to capture an Oddish and show it to Bill. I did it, and it validated the quest, but Bill keeps asking me to bring him an Oddish. I'm stuck in the storyline because I need to complete this quest chain to be able to battle the final gym

2023-05-23 20:05 UTC, DraKay commented
First you should open a bug thread instead of commenting in the pr

Second did you caught all the grass pokemon and caught a oddish **again**

Third this quest is not necessary and don't lock any gym