Implemented log book settings to allow disabling saving logs books pe…
pokeclicker/pokeclicker pull request #3889
Opened 2023-01-30 22:29 UTC by Vodovik

…r type (CLOSES #3725)
![image](https://user-images.githubusercontent.com/25463975/215610519-4c2f0457-69f7-4851-ba09-48dc7b9b09ce.png)

2023-03-20 08:08 UTC, Jaaslet requested changes
(have not tested yet) Can we move the settings to the settings window?

2023-03-20 08:40 UTC, Vodovik commented
@Jaaslet, @Aegyo requested that these settings be put in the logbook modal, so i put it there! : )

2023-04-05 00:17 UTC, Aegyo commented on src/components/logBookModal.html
> +</script>
This isn't needed, the templates defined in the setting modal file should be available to use over here too

2023-04-05 00:17 UTC, Aegyo commented on src/components/logBookModal.html
> +                                <tr data-bind="template: { name: 'BooleanSettingTemplate', data: Settings.getSetting(`logBook.${$data}`)}"></tr>
BooleanSettingSliderTemplate looks nicer I think

2023-04-05 00:17 UTC, Aegyo commented on src/modules/logbook/LogBook.ts
> +        if (this.canLog(`logBook.${type.label}`)) {
I don't like how you have to know how the settings names are set up to call `canLog` - I would prefer if `canLog` had the whole LogBookType as the parameter and then that function can do the dirty work of calculating the setting name we need.

2023-04-05 00:19 UTC, Aegyo commented
> (have not tested yet) Can we move the settings to the settings window?

I was thinking this didn't have a good location in the settings window, and seemed too small to warrant a new tab. Also just felt like it made more sense being on the modal the settings affect? Not sure, maybe it could be in both modals.

2023-04-08 19:43 UTC, Aegyo approved these changes

2023-04-08 19:45 UTC, Jaaslet approved these changes

2023-04-09 00:27 UTC, merged