Surprise Togepi fix + new quest type
pokeclicker/pokeclicker pull request #4135
Opened 2023-04-14 00:24 UTC by RegisCoaxans

I added DefeatDungeonBossQuest, which, obviously, requires the player to defeat a specific boss in a dungeon, both trainer or wild pokémon work !
As an introduction, I fixed Surprise Togepi passively ruining its questline in BF.

2023-04-29 04:22 UTC, osherwott reviewed
Could you add this requirement to the Parasect in the Manaphy Quest and subsequently remove the extra requirements for the regular Eterna Forest bosses?

2023-04-29 13:47 UTC, RegisCoaxans commented
Parasect is done.
Any other occurrence of this configuration that you know ?

2023-04-29 18:21 UTC, osherwott commented
There are a few questionable dungeon clears that could benefit from this, but completely replacing questline steps is best left for another time, since it's a matter of content rather than code cleanup. As far as this PR's concerned, all's good 👍

2023-04-30 09:46 UTC, Jaaslet requested changes

2023-04-30 09:46 UTC, Jaaslet commented on src/scripts/quests/questTypes/DefeatDungeonBossQuest.ts
> +                    this.targetEncountered = true;
I don't like pure computed setting other values. Those should be pure computed too

2023-04-30 09:46 UTC, Jaaslet commented on src/scripts/quests/questTypes/DefeatDungeonBossQuest.ts
> +    constructor(public dungeon: string, private tmpTarget : string, reward: (() => void) | number = 0, description?: string, onLoad?: (() => void)) {
`tmpTarget` is not very tmp, when we keep it around

2023-05-03 21:11 UTC, Jaaslet approved these changes
Looks good. Thanks for the PR

2023-05-03 21:11 UTC, merged