Added some basic Safari Zone Achievements
pokeclicker/pokeclicker pull request #4300
Opened 2023-05-13 08:52 UTC by Jaaslet

## Description

Adds achievements for bait, rocks, steps and items in the safari zone.
Only added some very basic/easy to get, because there is a chance this will be released before friend safari is out, and it will be mean to force players to do a lot of safari zone stuff, before we finish the rework

## Motivation and Context

We need more stuff to make the safari zone fun, and i think achievements are easy to add, and give a small reward for doing stuff (and rewards are fun)

## How Has This Been Tested?

Did stuff in the safari zone and saw the achievement numbers go up

## Types of changes

- Improving existing feature

2023-05-13 08:55 UTC, Jaaslet commented
The plan is to add more achievements right before we release friend safari

2023-05-28 11:55 UTC, Farboo171 requested changes
Changed "the" to "a" to reflect that these may be achieved in any safari zone.

2023-05-28 11:55 UTC, Farboo171 commented on src/modules/requirements/SafariBaitRequirement.ts
> +        return `${this.requiredValue} Bait needs to be thrown in the Safari Zone.`;
```suggestion
        return `${this.requiredValue} Bait needs to be thrown in a Safari Zone.`;
```

2023-05-28 11:55 UTC, Farboo171 commented on src/modules/requirements/SafariItemsRequirement.ts
> +        return `${this.requiredValue} Items needs to be picked up in the Safari Zone.`;
```suggestion
        return `${this.requiredValue} Items needs to be picked up in a Safari Zone.`;
```

2023-05-28 11:55 UTC, Farboo171 commented on src/modules/requirements/SafariRocksRequirement.ts
> +        return `${this.requiredValue} Rocks needs to be thrown in the Safari Zone.`;
```suggestion
        return `${this.requiredValue} Rocks needs to be thrown in a Safari Zone.`;
```

2023-05-28 11:55 UTC, Farboo171 commented on src/modules/requirements/SafariStepsRequirement.ts
> +        return `${this.requiredValue} Steps needs to be taken in the Safari Zone.`;
```suggestion
        return `${this.requiredValue} Steps needs to be taken in a Safari Zone.`;
```

2023-05-28 11:55 UTC, Farboo171 commented on src/scripts/achievements/AchievementHandler.ts
> +        AchievementHandler.addAchievement('Who dropped these here?', 'Pick up 10 Items in the Safari Zone', new SafariItemsRequirement(10), 0.2);
```suggestion
        AchievementHandler.addAchievement('Who dropped these here?', 'Pick up 10 Items in a Safari Zone', new SafariItemsRequirement(10), 0.2);
```

2023-05-28 11:55 UTC, Farboo171 commented on src/scripts/achievements/AchievementHandler.ts
> +        AchievementHandler.addAchievement('This is not a Pokéball!', 'Throw 10 Rocks in the Safari Zone', new SafariRocksRequirement(10), 0.2);
```suggestion
        AchievementHandler.addAchievement('This is not a Pokéball!', 'Throw 10 Rocks in a Safari Zone', new SafariRocksRequirement(10), 0.2);
```

2023-05-28 11:55 UTC, Farboo171 commented on src/scripts/achievements/AchievementHandler.ts
> +        AchievementHandler.addAchievement('Hope it likes berries', 'Throw 10 Bait in the Safari Zone', new SafariBaitRequirement(10), 0.2);
```suggestion
        AchievementHandler.addAchievement('Hope it likes berries', 'Throw 10 Bait in a Safari Zone', new SafariBaitRequirement(10), 0.2);
```

2023-05-28 11:55 UTC, Farboo171 commented on src/scripts/achievements/AchievementHandler.ts
> +        AchievementHandler.addAchievement('Gotta get your steps in!', 'Walk 100 Steps in the Safari Zone', new SafariStepsRequirement(100), 0.2);
```suggestion
        AchievementHandler.addAchievement('Gotta get your steps in!', 'Walk 100 Steps in a Safari Zone', new SafariStepsRequirement(100), 0.2);
```

2023-05-28 23:10 UTC, Aegyo approved these changes

2023-05-28 23:11 UTC, merged