Category Improvements (part 1)
pokeclicker/pokeclicker pull request #4331
Opened 2023-05-19 01:17 UTC by CypherX

## Description
The first step of my plan to improve categories and make them more useful.

- Categories can now be re-ordered in the Edit Categories modal, this order will be reflected everywhere they are displayed.
- Ability to move all pokemon from one category to another category.
- Remove Category button hidden for the None & Favorite categories as we do not allow the player to remove those.

(Thanks Jessica for fixing the sortable binding code)

## Motivation and Context
Categories are neat but also limited in their usefulness. This aims to improve that usefulness and overall management of categories.

## How Has This Been Tested?
Re-ordered categories & reloaded the page to verify the order persisted.
Moved pokemon between categories several times.

## Screenshots (optional):
![image](https://github.com/pokeclicker/pokeclicker/assets/672420/ff10c273-8f59-41cd-be5c-bb03bba7f9bb)
![image](https://github.com/pokeclicker/pokeclicker/assets/672420/e676fb71-153d-4e3c-810a-c6784a9f52be)

## Types of changes
- Feature update
- UI improvement

2023-05-19 01:25 UTC, CypherX commented
Additional plans for categories (disclaimer: none of these are guaranteed):

- Assign a pokemon to multiple categories
- Filter by multiple categories in the pokedex/hatchery
- Ability to assign hatchery helpers to a specific category
- Use icons/shapes to differentiate categories in addition to color?
- Category pokeball filter?

2023-05-24 15:50 UTC, Jaaslet requested changes
- If you switch the two bottom categories, and then deletes the bottom, they both go away
Other than that, it looks good

2023-05-24 15:50 UTC, Jaaslet commented on src/modules/party/Category.ts
> +        if (!json || !json.categories) {
```suggestion
        if (!json?.categories) {
```

2023-05-25 04:23 UTC, CypherX commented
> * If you switch the two bottom categories, and then deletes the bottom, they both go away
>       Other than that, it looks good

Fixed (thanks Jess for the ko sortable fix. Note that the change in `pokeballSelectorAdvModal.html` is related to this)

2023-05-25 06:41 UTC, Jaaslet approved these changes
Looks good. Thanks for the PR

2023-05-25 06:41 UTC, merged