Buff idleable quests
pokeclicker/pokeclicker pull request #757
Opened 2020-09-22 06:11 UTC by anapple96

Received quite a bit of complains regarding QP

2020-09-23 03:00 UTC, RedSparr0w requested changes
Some of the numbers seem to be a little high, and some are being double/triple buffed due to relying on already buffed values.

2020-09-23 05:50 UTC, anapple96 commented on src/scripts/GameConstants.ts
> +    export const DEFEAT_POKEMONS_BASE_REWARD  = questBase * 3;
Yeah, that wasn't intended, 9x buff is too high

2020-09-23 05:52 UTC, anapple96 commented on src/scripts/GameConstants.ts
> +    export const CAPTURE_POKEMONS_BASE_REWARD = DEFEAT_POKEMONS_BASE_REWARD / 0.5; // Defeat reward divided by chance to catch (guessed)
Nerfed defeat base

2020-09-23 05:53 UTC, anapple96 commented on src/scripts/GameConstants.ts
> +    export const GAIN_MONEY_BASE_REWARD       = questBase * 0.005;  // Dimava
Nerfed it a bit

2020-09-28 09:06 UTC, RedSparr0w commented on src/scripts/GameConstants.ts
> +    export const GAIN_TOKENS_BASE_REWARD      = CAPTURE_POKEMONS_BASE_REWARD / 9; // <route number> tokens gained for every capture
This one is still nearly 4x as much as it previously was.

2020-10-15 02:58 UTC, closed without merging